# Generated by Django 3.1.7 on 2021-05-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimates', '0006_auto_20210513_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_fact', models.IntegerField(default=0)),
                ('purchased_doc', models.IntegerField(default=0)),
                ('purchased_ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimates.estimate')),
            ],
        ),
    ]
