# Generated by Django 3.1.7 on 2021-05-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_ware',
            new_name='ware',
        ),
    ]
