# Generated by Django 3.1.7 on 2021-08-19 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210814_1114'),
        ('estimates', '0010_auto_20210718_1051'),
        ('purchases', '0002_auto_20210525_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='ware',
        ),
        migrations.AddField(
            model_name='purchase',
            name='system_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ware_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ware_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.estimate'),
        ),
    ]
