# Generated by Django 3.1.7 on 2021-08-19 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0012_remove_estimate_purchases'),
        ('purchases', '0004_remove_purchase_ware_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ware_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.estimate'),
        ),
    ]
