# Generated by Django 3.1.7 on 2021-08-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_delete_invoicedetails'),
        ('core', '0015_auto_20210814_1114'),
        ('purchases', '0005_purchase_ware_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='object_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.object'),
        ),
    ]
