# Generated by Django 3.1.7 on 2021-08-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0013_nonestimate'),
        ('purchases', '0006_auto_20210823_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='ware_reference',
            new_name='estimate_reference',
        ),
        migrations.AddField(
            model_name='purchase',
            name='non_estimate_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.nonestimate'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_doc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_fact',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='NonEstimatePurchaseQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchases_fact', models.FloatField(default=0)),
                ('purchases_doc', models.FloatField(default=0)),
                ('non_estimate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estimates.nonestimate')),
            ],
        ),
        migrations.CreateModel(
            name='EstimatePurchaseQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchases_fact', models.FloatField(default=0)),
                ('purchases_doc', models.FloatField(default=0)),
                ('estimate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estimates.estimate')),
            ],
        ),
    ]
