# Generated by Django 3.1.7 on 2021-08-31 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0013_nonestimate'),
        ('purchases', '0008_purchase_estimate_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatepurchasequantity',
            name='estimate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchased', to='estimates.estimate'),
        ),
    ]
