# Generated by Django 3.1.7 on 2021-09-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210814_1114'),
        ('estimates', '0013_nonestimate'),
        ('purchases', '0009_auto_20210831_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatepurchasequantity',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.object'),
        ),
        migrations.AddField(
            model_name='nonestimatepurchasequantity',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.object'),
        ),
        migrations.AlterField(
            model_name='estimatepurchasequantity',
            name='estimate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_purchased', to='estimates.estimate'),
        ),
        migrations.AlterField(
            model_name='nonestimatepurchasequantity',
            name='non_estimate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nonestimate_purchased', to='estimates.nonestimate'),
        ),
    ]
