# Generated by Django 3.1.7 on 2021-09-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20210901_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatepurchasequantity',
            old_name='estimate',
            new_name='estimate_reference',
        ),
        migrations.RenameField(
            model_name='nonestimatepurchasequantity',
            old_name='non_estimate',
            new_name='non_estimate_reference',
        ),
    ]
