# Generated by Django 3.1.7 on 2021-09-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_auto_20210906_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
