# Generated by Django 3.1.7 on 2021-09-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_purchase_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='estimate_bool',
            new_name='assigned',
        ),
    ]
