# Generated by Django 3.1.7 on 2021-09-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_auto_20210930_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
