# Generated by Django 3.1.7 on 2021-10-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210814_1114'),
        ('purchases', '0015_auto_20210930_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='units',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unit'),
        ),
    ]
