# Generated by Django 3.1.7 on 2021-11-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210814_1114'),
        ('purchases', '0016_purchase_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatepurchasequantity',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system'),
        ),
        migrations.AddField(
            model_name='nonestimatepurchasequantity',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system'),
        ),
    ]
