# Generated by Django 3.1.7 on 2021-06-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0002_auto_20210616_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablejournal',
            name='length',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
