# Generated by Django 3.1.7 on 2021-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0003_auto_20210617_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablejournal',
            name='start',
            field=models.IntegerField(default=1),
        ),
    ]
