# Generated by Django 3.1.7 on 2021-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0004_cablejournal_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cablejournal',
            old_name='name',
            new_name='end',
        ),
        migrations.RemoveField(
            model_name='cablejournal',
            name='number',
        ),
        migrations.AlterField(
            model_name='cablejournal',
            name='start',
            field=models.CharField(max_length=150),
        ),
    ]
