# Generated by Django 3.1.7 on 2021-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0005_auto_20210618_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablejournal',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
