# Generated by Django 3.1.7 on 2021-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0006_cablejournal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablejournal',
            name='isolation',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
