# Generated by Django 3.1.7 on 2021-08-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0008_auto_20210721_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablejournal',
            name='cores',
            field=models.IntegerField(default=2),
        ),
    ]
