# Generated by Django 3.1.7 on 2021-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0010_auto_20210817_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablejournal',
            name='cores',
            field=models.CharField(max_length=5),
        ),
    ]
