// Authentication actions
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
// Login actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
// Logout actions
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
// Updating profile actions
export const PROFILE_CHANGE_SUCCESS = 'PROFILE_CHANGE_SUCCESS';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
// Error handling
export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_HIDE = 'ERROR_HIDE';
// Invoice handling
export const INVOICE_NEW_CREATE = 'INVOICE_NEW_CREATE';
export const INVOICES_LOAD_SUCCESS = 'INVOICES_LOAD_SUCCESS';
export const INVOICES_LOAD_FAIL = 'INVOICES_LOAD_FAIL';
// Estimates loading handling
export const ESTIMATES_LOAD_SUCCESS = 'ESTIMATES_LOAD_SUCCESS';
export const ESTIMATES_LOAD_FAIL = 'ESTIMATES_LOAD_FAIL';
export const ESTIMATES_UNLOAD_SUCCESS = 'ESTIMATES_UNLOAD_SUCCESS';
// Estimates manipulation handling
export const ESTIMATE_ROW_EDIT_START = 'ESTIMATE_ROW_EDIT_START';
export const ESTIMATE_ROW_EDIT_SUCCESS = 'ESTIMATE_ROW_EDIT_SUCCESS';
export const ESTIMATE_ROW_EDIT_FAIL = 'ESTIMATE_ROW_EDIT_FAIL';
export const ESTIMATE_ROW_DELETE_START = 'ESTIMATE_ROW_DELETE_START';
export const ESTIMATE_ROW_DELETE_SUCCESS = 'ESTIMATE_ROW_DELETE_SUCCESS';
export const ESTIMATE_ROW_DELETE_FAIL = 'ESTIMATE_ROW_DELETE_FAIL';
export const ESTIMATE_ROW_ADD_SUCCESS = 'ESTIMATE_ROW_ADD_SUCCESS';
export const ESTIMATE_ROW_ADD_FAIL = 'ESTIMATE_ROW_ADD_FAIL';
// Estimates systems handling
export const ESTIMATE_SYSTEMS_LOAD_SUCCESS = 'ESTIMATE_SYSTEMS_LOAD_SUCCESS';
export const ESTIMATE_SYSTEMS_LOAD_FAIL = 'ESTIMATE_SYSTEMS_LOAD_FAIL'
// Info handling
export const INFO_PAGE_NAME_LOAD = 'INFO_PAGE_NAME_LOAD';
export const INFO_MESSAGE_SHOW = 'INFO_MESSAGE_SHOW';
export const INFO_MESSAGE_HIDE = 'INFO_MESSAGE_HIDE';
// Snackbar handling
export const SNACK_SHOW = 'SNACK_SHOW';
export const SNACK_HIDE = 'SNACK_HIDE';
// Objects handling
export const OBJECTS_LOAD_SUCCESS = 'OBJECTS_LOAD_SUCCESS';
export const OBJECTS_LOAD_FAIL = 'OBJECTS_LOAD_FAIL';
// Undo handling
export const UNDO_DATA_SAVE = 'UNDO_DATA_SAVE';
export const UNDO_ESTIMATE_ROW_DELETE = 'UNDO_ESTIMATE_ROW_DELETE';
export const UNDO_ESTIMATE_ROW_EDIT = 'UNDO_ESTIMATE_ROW_EDIT';
export const UNDO_ESTIMATE_ROW_ADD = 'UNDO_ESTIMATE_ROW_ADD';
// Search handling
export const SEARCH_ESTIMATES = 'SEARCH_ESTIMATES';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_STOP = 'SEARCH_STOP';
// Contractors handling
export const CONTRACTOR_LIST_LOAD = 'CONTRACTOR_LIST_LOAD';
export const CONTRACTOR_DETAILS_LOAD = 'CONTRACTOR_DETAILS_LOAD';