// Authentication actions
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
// Login actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
// Logout actions
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
// Updating profile actions
export const PROFILE_CHANGE_SUCCESS = 'PROFILE_CHANGE_SUCCESS';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
// Error handling
export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_HIDE = 'ERROR_HIDE';
// Invoice handling
export const INVOICE_NEW_CREATE = 'INVOICE_NEW_CREATE';
export const INVOICES_LOAD_SUCCESS = 'INVOICES_LOAD_SUCCESS';
export const INVOICES_LOAD_FAIL = 'INVOICES_LOAD_FAIL';
// Estimates loading handling
export const ESTIMATES_LOAD_SUCCESS = 'ESTIMATES_LOAD_SUCCESS';
export const ESTIMATES_LOAD_FAIL = 'ESTIMATES_LOAD_FAIL';
export const ESTIMATES_UNLOAD_SUCCESS = 'ESTIMATES_UNLOAD_SUCCESS';
// Estimates manipulation handling
export const ESTIMATE_ROW_EDIT_START = 'ESTIMATE_ROW_EDIT_START';
export const ESTIMATE_ROW_EDIT_SUCCESS = 'ESTIMATE_ROW_EDIT_SUCCESS';
export const ESTIMATE_ROW_EDIT_FAIL = 'ESTIMATE_ROW_EDIT_FAIL';
export const ESTIMATE_ROW_DELETE_START = 'ESTIMATE_ROW_DELETE_START';
export const ESTIMATE_ROW_DELETE_SUCCESS = 'ESTIMATE_ROW_DELETE_SUCCESS';
export const ESTIMATE_ROW_DELETE_FAIL = 'ESTIMATE_ROW_DELETE_FAIL';
export const ESTIMATE_ROW_ADD_SUCCESS = 'ESTIMATE_ROW_ADD_SUCCESS';
export const ESTIMATE_ROW_ADD_FAIL = 'ESTIMATE_ROW_ADD_FAIL';
// Estimates systems handling
export const ESTIMATE_SYSTEMS_LOAD_SUCCESS = 'ESTIMATE_SYSTEMS_LOAD_SUCCESS';
export const ESTIMATE_SYSTEMS_LOAD_FAIL = 'ESTIMATE_SYSTEMS_LOAD_FAIL'
// Info handling
export const INFO_PAGE_NAME_LOAD = 'INFO_PAGE_NAME_LOAD';
export const INFO_MESSAGE_SHOW = 'INFO_MESSAGE_SHOW';
export const INFO_MESSAGE_HIDE = 'INFO_MESSAGE_HIDE';
export const INFO_LOADING_SPINNER_SHOW ='INFO_LOADING_SPINNER_SHOW';
export const INFO_LOADING_SPINNER_HIDE = 'INFO_LOADING_SPINNER_HIDE';
// Snackbar handling
export const SNACK_SHOW = 'SNACK_SHOW';
export const SNACK_HIDE = 'SNACK_HIDE';
// Objects handling
export const OBJECTS_LOAD_SUCCESS = 'OBJECTS_LOAD_SUCCESS';
export const OBJECTS_LOAD_FAIL = 'OBJECTS_LOAD_FAIL';
// Undo handling
export const UNDO_DATA_SAVE = 'UNDO_DATA_SAVE';
export const UNDO_CLEAR = 'UNDO_CLEAR';
export const UNDO_CABLE_JOURNAL_ROW_ADD = 'UNDO_CABLE_JOURNAL_ROW_ADD';
export const UNDO_CABLE_JOURNAL_ROW_REMOVE = 'UNDO_CABLE_JOURNAL_ROW_REMOVE';
export const UNDO_CABLE_JOURNAL_DATA_SAVE = 'UNDO_CABLE_JOURNAL_DATA_SAVE';
// Search handling
export const SEARCH_ESTIMATES = 'SEARCH_ESTIMATES';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_STOP = 'SEARCH_STOP';
// Contractors handling
export const CONTRACTOR_LIST_LOAD = 'CONTRACTOR_LIST_LOAD';
export const CONTRACTOR_DETAILS_LOAD = 'CONTRACTOR_DETAILS_LOAD';
export const CONTRACTOR_DETAILS_UNLOAD = 'CONTRACTOR_DETAILS_UNLOAD';
export const CONTRACTOR_DETAILS_UPDATE = 'CONTRACTOR_DETAILS_UPDATE';
export const CONTRACTOR_ADD_SUCCESS = 'CONTRACTOR_ADD_SUCCESS';
export const CONTRACTOR_TYPES_LOAD = 'CONTRACTOR_TYPES_LOAD';
export const CONTRACTOR_LIST_SPINNER_SHOW = 'CONTRACTOR_LIST_SPINNER_SHOW';
export const CONTRACTOR_LIST_SPINNER_HIDE = 'CONTRACTOR_LIST_SPINNER_HIDE';
export const CONTRACTOR_DATA_SPINNER_SHOW = 'CONTRACTOR_DATA_SPINNER_SHOW';
export const CONTRACTOR_DATA_SPINNER_HIDE = 'CONTRACTOR_DATA_SPINNER_HIDE';
export const CONTRACTOR_REPRESENTATIVES_DATA_LOAD = 'CONTRACTOR_REPRESENTATIVES_DATA_LOAD';
export const CONTRACTOR_REPRESENTATIVE_ADD = 'CONTRACTOR_REPRESENTATIVE_ADD';
export const CONTRACTOR_REPRESENTATIVE_REMOVE = 'CONTRACTOR_REPRESENTATIVE_REMOVE';
export const CONTRACTOR_REPRESENTATIVE_EDIT = 'CONTRACTOR_REPRESENTATIVE_EDIT';
// Cable journal handling
export const CABLE_JOURNAL_DEVICE_ADD = 'CABLE_JOURNAL_DEVICE_ADD';
export const CABLE_JOURNAL_DEVICE_REMOVE = 'CABLE_JOURNAL_DEVICE_REMOVE';
export const CABLE_JOURNAL_ROWS_UPDATE = 'CABLE_JOURNAL_ROWS_UPDATE';
export const CABLE_JOURNAL_LOAD_SUCCESS = 'CABLE_JOURNAL_LOAD_SUCCESS';
// Delete handling
export const DELETE_SNACK_SHOW = 'DELETE_SNACK_SHOW';
export const DELETE_SNACK_HIDE = 'DELETE_SNACK_HIDE';
export const DELETE_CABLE_JOURNAL_ITEM_ADD = 'DELETE_CABLE_JOURNAL_ITEM_ADD';
export const DELETE_CABLE_JOURNAL_ITEM_REMOVE = 'DELETE_CABLE_JOURNAL_ITEM_REMOVE';
export const DELETE_CABLE_JOURNAL_REMOVE_ALL = 'DELETE_CABLE_JOURNAL_REMOVE_ALL';
export const DELETE_CABLE_JOURNAL_ADD_ALL = 'DELETE_CABLE_JOURNAL_ADD_ALL';