# Generated by Django 3.1.7 on 2021-07-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210602_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('patron_name', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.contractor')),
            ],
        ),
    ]
