# Generated by Django 3.1.7 on 2021-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210706_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='representative',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='representative',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
