# Generated by Django 3.1.7 on 2021-07-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210706_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representative',
            old_name='manager_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='representative',
            old_name='manager_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='manager_phone',
        ),
    ]
