# Generated by Django 3.1.7 on 2021-07-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210706_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='object',
            name='contractors',
            field=models.ManyToManyField(to='core.Contractor'),
        ),
    ]
