# Generated by Django 3.1.7 on 2021-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210709_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
