# Generated by Django 3.1.7 on 2021-08-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='type',
        ),
        migrations.AlterField(
            model_name='representative',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.contractor'),
        ),
    ]
