# Generated by Django 3.1.7 on 2021-04-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='note',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
