# Generated by Django 3.1.7 on 2021-05-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_auto_20210511_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='note',
            field=models.CharField(default='', max_length=150),
        ),
    ]
