# Generated by Django 3.1.7 on 2021-05-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_auto_20210511_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='note',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
