# Generated by Django 3.1.7 on 2021-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_auto_20210513_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='units',
            field=models.CharField(choices=[('шт.', 'шт.'), ('м.', 'м.'), ('км.', 'км.'), ('кг.', 'кг.'), ('г.', 'г.'), ('компл.', 'компл.'), ('упак.', 'упак.'), ('набор', 'набор')], default='шт', max_length=15),
        ),
    ]
