# Generated by Django 3.1.7 on 2021-07-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210709_0418'),
        ('estimates', '0007_auto_20210601_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_number', models.IntegerField(default=1)),
                ('ware_number', models.IntegerField(default=1)),
                ('ware', models.CharField(max_length=250)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=150)),
                ('object', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.object')),
                ('system', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.system')),
                ('units', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estimates.unit')),
            ],
        ),
    ]
