# Generated by Django 3.1.7 on 2021-07-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_unit'),
        ('estimates', '0009_auto_20210718_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.system'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='units',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.unit'),
        ),
        migrations.DeleteModel(
            name='EstimateTest',
        ),
    ]
