# Generated by Django 3.1.7 on 2021-08-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_purchase_ware_reference'),
        ('estimates', '0010_auto_20210718_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='purchases',
            field=models.ManyToManyField(to='purchases.Purchase'),
        ),
    ]
