# Generated by Django 3.1.7 on 2021-08-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0011_estimate_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='purchases',
        ),
    ]
