# Generated by Django 3.1.7 on 2021-08-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210814_1114'),
        ('estimates', '0012_remove_estimate_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware', models.CharField(max_length=250)),
                ('quantity', models.FloatField(default=0)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.object')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system')),
                ('units', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.unit')),
            ],
        ),
    ]
