# Generated by Django 3.1.7 on 2021-03-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150)),
                ('contractor', models.CharField(max_length=150)),
                ('inv_date', models.DateField()),
            ],
        ),
    ]
