# Generated by Django 3.1.7 on 2021-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210601_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='units',
            field=models.CharField(choices=[('шт.', 'шт.'), ('м.', 'м.'), ('км.', 'км'), ('кг.', 'кг.'), ('г.', 'г.'), ('компл.', 'компл.'), ('упак.', 'упак.'), ('набор', 'набор')], default='шт.', max_length=15),
        ),
    ]
