# Generated by Django 3.1.7 on 2021-06-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20210601_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='quantity_bought',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='quantity_docs',
            field=models.FloatField(default=0),
        ),
    ]
