# Generated by Django 3.1.7 on 2021-06-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210602_2247'),
        ('invoices', '0008_auto_20210602_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.contractor'),
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
