# Generated by Django 3.1.7 on 2021-08-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20210602_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceDetails',
        ),
    ]
