# Generated by Django 3.1.7 on 2021-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20210929_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='not_received',
            field=models.IntegerField(default=0),
        ),
    ]
